
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author japin
 */
public class PeripheralsFrame extends javax.swing.JFrame {

    private DefaultTableModel model;

    /**
     * Creates new form PeripheralsFrame
     */
    public PeripheralsFrame() {
        initComponents();
        this.populateTable();
    }

    private void populateTable() {
        var resData = Peripherals.peripherals();
        for (var data : resData) {
            String deviceCode = data[0];
            String name = data[1];
            String peripheral = data[2];
            String assignedTo = data[3];

            Object[] newRow = {deviceCode, name, peripheral, assignedTo};
            model = (DefaultTableModel) peripheralsTable.getModel();
            model.addRow(newRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        peripheralsTable = new javax.swing.JTable();
        deviceName = new javax.swing.JTextField();
        peripheralType = new javax.swing.JTextField();
        assignedTo = new javax.swing.JTextField();
        deviceNameLabel = new javax.swing.JLabel();
        peripheralLabel = new javax.swing.JLabel();
        assignmentLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        peripheralsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Device code", "Name", "Peripherals", "Assigned to"
            }
        ));
        peripheralsTable.setColumnSelectionAllowed(true);
        peripheralsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peripheralsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(peripheralsTable);
        peripheralsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        deviceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceNameActionPerformed(evt);
            }
        });

        deviceNameLabel.setText("Device Name:");

        peripheralLabel.setText("Peripheral Type:");

        assignmentLabel.setText("Assigned to:");

        addBtn.setBackground(new java.awt.Color(255, 102, 102));
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(102, 204, 0));
        updateBtn.setText("UPDATE");
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(peripheralType, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(deviceName)
                            .addComponent(assignedTo))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                    .addComponent(deviceNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peripheralLabel)
                    .addComponent(assignmentLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(deviceNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(peripheralLabel)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(peripheralType))
                .addGap(18, 18, 18)
                .addComponent(assignmentLabel)
                .addGap(5, 5, 5)
                .addComponent(assignedTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deviceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceNameActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String device_name = deviceName.getText();
        String peripheral = peripheralType.getText();
        String assigned_to = assignedTo.getText();

        if (device_name.isEmpty() && peripheral.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill in all the fields!");
        } else {
            var resData = Peripherals.create(device_name, peripheral, assigned_to);
            if (resData.get("success").toString().equals("true")) {
                 JOptionPane.showMessageDialog(new JFrame(), "Added successfully!");
                model.setRowCount(0);
                this.populateTable();
            } else {
                System.out.println(resData);
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void peripheralsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peripheralsTableMouseClicked
        model = (DefaultTableModel) peripheralsTable.getModel();

        //fecth when row is selected
        String name = model.getValueAt(peripheralsTable.getSelectedRow(), 1).toString();
        String peripheral = model.getValueAt(peripheralsTable.getSelectedRow(), 2).toString();
        String assigned_to = model.getValueAt(peripheralsTable.getSelectedRow(), 3).toString();

        //set to text field
        deviceName.setText(name);
        peripheralType.setText(peripheral);
        assignedTo.setText(assigned_to);
    }//GEN-LAST:event_peripheralsTableMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here:
        String device_code = model.getValueAt(peripheralsTable.getSelectedRow(), 0).toString();
        String device_name = deviceName.getText();
        String peripheral = peripheralType.getText();
        String assigned_to = assignedTo.getText();

        if (device_name.isEmpty() && peripheral.isEmpty()) {
            JOptionPane.showMessageDialog(new JFrame(), "Please fill in all the fields!");
        } else {
            var resData = Peripherals.update(device_code, device_name, peripheral, assigned_to);
            if (resData.get("success").toString().equals("true")) {
                 JOptionPane.showMessageDialog(new JFrame(), "Updated Successfully!");
                model.setRowCount(0);
                this.populateTable();
            } else {
                System.out.println(resData);
            }
        }
    }//GEN-LAST:event_updateBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeripheralsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeripheralsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeripheralsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeripheralsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeripheralsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField assignedTo;
    private javax.swing.JLabel assignmentLabel;
    private javax.swing.JTextField deviceName;
    private javax.swing.JLabel deviceNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel peripheralLabel;
    private javax.swing.JTextField peripheralType;
    private javax.swing.JTable peripheralsTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
